#!/usr/bin/env bash
# sync.sh
# Generates Cursor command files from installed skills for @skill-name.md chat references.
# Works on macOS and Linux. No external dependencies required.
#
# Usage:
#   bash sync.sh                    # sync all skills
#   bash sync.sh --global-only      # skip project-level skills
#   bash sync.sh --help             # show usage

set -euo pipefail

VERSION="1.0.0"

# ─── Config ────────────────────────────────────────────────────────────────────

GLOBAL_SKILLS_DIR="${HOME}/.agents/skills"
CURSOR_SKILLS_DIR="${HOME}/.cursor/skills-cursor"
GLOBAL_COMMANDS_DIR="${HOME}/.cursor/commands"

# ─── Flags ─────────────────────────────────────────────────────────────────────

GLOBAL_ONLY=false

for arg in "$@"; do
  case "$arg" in
    --global-only) GLOBAL_ONLY=true ;;
    --help|-h)
      echo "sync.sh v${VERSION} — Cursor Skill Command Sync"
      echo ""
      echo "Usage: bash sync.sh [--global-only] [--help]"
      echo ""
      echo "Scans skill directories and generates one .md command file per skill"
      echo "in ~/.cursor/commands/, enabling @<skill-name>.md references in chat."
      echo ""
      echo "Skill directories scanned:"
      echo "  ~/.agents/skills/          (global skills from npx skills add)"
      echo "  ~/.cursor/skills-cursor/   (Cursor built-in skills)"
      echo "  ./.agents/skills/          (project-level skills, current directory)"
      echo ""
      echo "Output:"
      echo "  ~/.cursor/commands/<skill-name>.md   (global + cursor skills)"
      echo "  ./.cursor/commands/<skill-name>.md   (project-level skills)"
      exit 0
      ;;
  esac
done

# ─── Helpers ───────────────────────────────────────────────────────────────────

count_generated=0
count_skipped=0

log()     { printf "  %s\n" "$*"; }
success() { printf "  ✓ %s\n" "$*"; }

generate_command() {
  local skill_dir="$1"
  local commands_dir="$2"
  local skill_file="${skill_dir}/SKILL.md"

  [[ -f "$skill_file" ]] || return 0

  local skill_name
  skill_name="$(basename "$skill_dir")"
  local output_file="${commands_dir}/${skill_name}.md"

  local file_list
  file_list="$(ls "$skill_dir" 2>/dev/null)"

  local display_path="${skill_dir/#$HOME/~}"

  mkdir -p "$commands_dir"

  cat > "$output_file" <<EOF
# ${skill_name}

<!-- Auto-generated by sync.sh (skill-command-sync) — do not edit manually -->
<!-- Source: ${skill_file} -->

**Skill Location:** \`${display_path}/\`

## Files in This Skill

\`\`\`
${file_list}
\`\`\`

---

$(cat "$skill_file")
EOF

  success "Generated: ${output_file/#$HOME/~}"
  count_generated=$(( count_generated + 1 ))
}

scan_dir() {
  local skills_dir="$1"
  local commands_dir="$2"
  local label="$3"

  if [[ ! -d "$skills_dir" ]]; then
    log "Skipping ${label} (not found: ${skills_dir/#$HOME/~})"
    return 0
  fi

  log "Scanning ${label}: ${skills_dir/#$HOME/~}"

  local found=0
  for skill_dir in "$skills_dir"/*/; do
    [[ -d "$skill_dir" ]] || continue
    if [[ ! -f "${skill_dir}SKILL.md" ]]; then
      count_skipped=$(( count_skipped + 1 ))
      continue
    fi
    generate_command "${skill_dir%/}" "$commands_dir"
    found=$(( found + 1 ))
  done

  [[ $found -eq 0 ]] && log "  No skills found."
}

# ─── Main ──────────────────────────────────────────────────────────────────────

printf "\n🔄 Cursor Skill Command Sync v%s\n\n" "$VERSION"

scan_dir "$GLOBAL_SKILLS_DIR"  "$GLOBAL_COMMANDS_DIR" "global skills"
scan_dir "$CURSOR_SKILLS_DIR"  "$GLOBAL_COMMANDS_DIR" "cursor skills"

if [[ "$GLOBAL_ONLY" == "false" && -d ".agents/skills" ]]; then
  project_commands_dir="$(pwd)/.cursor/commands"
  scan_dir "$(pwd)/.agents/skills" "$project_commands_dir" "project skills ($(pwd))"
fi

# ─── Summary ───────────────────────────────────────────────────────────────────

printf "\n"
printf "  Generated : %d command file(s)\n" "$count_generated"
[[ $count_skipped -gt 0 ]] && printf "  Skipped   : %d dir(s) without SKILL.md\n" "$count_skipped"
printf "\n  Tip: type @<skill-name>.md in Cursor chat to attach full skill context.\n\n"
