#!/usr/bin/env bash
# uninstall.sh
# Removes skill-tags: deletes the sync script, removes the shell wrapper,
# and optionally deletes generated command files.

set -euo pipefail

SYNC_SCRIPT="${HOME}/.cursor/sync-skill-commands.sh"
COMMANDS_DIR="${HOME}/.cursor/commands"
MARKER="# ─── skill-tags / Cursor Skill Command Sync"

# Detect shell rc file
detect_rc() {
  if [[ -n "${ZSH_VERSION:-}" ]] || [[ "$(basename "${SHELL:-}")" == "zsh" ]]; then
    echo "${HOME}/.zshrc"
  else
    echo "${HOME}/.bash_profile"
  fi
}

RC_FILE="$(detect_rc)"

printf "\n🗑  skill-tags — Uninstaller\n\n"

# 1. Remove sync script
if [[ -f "$SYNC_SCRIPT" ]]; then
  rm "$SYNC_SCRIPT"
  printf "  ✓ Removed %s\n" "${SYNC_SCRIPT/#$HOME/~}"
else
  printf "  ~ Sync script not found (already removed?)\n"
fi

# 2. Remove shell wrapper from rc file
if grep -q "$MARKER" "$RC_FILE" 2>/dev/null; then
  # Remove the block from the marker line through the closing marker line
  local_tmp="$(mktemp)"
  awk "
    /${MARKER//\//\\/}/{found=1}
    found && /^# ─────/{if(++count==2){found=0; next}}
    !found
  " "$RC_FILE" > "$local_tmp"
  mv "$local_tmp" "$RC_FILE"
  printf "  ✓ Removed skills wrapper from %s\n" "${RC_FILE/#$HOME/~}"
else
  printf "  ~ Shell wrapper not found in %s\n" "${RC_FILE/#$HOME/~}"
fi

# 3. Optionally remove generated command files
printf "\n  Remove generated command files in %s? [y/N] " "${COMMANDS_DIR/#$HOME/~}"
read -r answer
if [[ "${answer,,}" == "y" ]]; then
  # Only remove auto-generated files (those with our comment marker)
  removed=0
  for f in "$COMMANDS_DIR"/*.md; do
    [[ -f "$f" ]] || continue
    if grep -q "Auto-generated by sync" "$f" 2>/dev/null; then
      rm "$f"
      removed=$(( removed + 1 ))
    fi
  done
  printf "  ✓ Removed %d generated command file(s)\n" "$removed"
else
  printf "  ~ Keeping generated command files.\n"
fi

printf "\n  Done. Restart your shell or run: source %s\n\n" "${RC_FILE/#$HOME/~}"
